### ISSUE TITLE
Library Binding Issue?

### ISSUE THREAD

**Issue by hnnhcohen** [luckybulldozer/VisualSFM_OS_X_Installer#26]
When I try to open VisualSFM it pops up for a minute and then disappears. I'm using a Mac 10.9.5. This is what it says: 

dyn-209-2-232-172:bin HannahJaneCohen$ ./VisualSFM 
dyld: lazy symbol binding failed: Symbol not found: _cairo_xlib_surface_create
  Referenced from: /usr/local/opt/gtk+/lib/libgdk-x11-2.0.0.dylib
  Expected in: /usr/local/opt/cairo/lib/libcairo.2.dylib

dyld: Symbol not found: _cairo_xlib_surface_create
  Referenced from: /usr/local/opt/gtk+/lib/libgdk-x11-2.0.0.dylib
  Expected in: /usr/local/opt/cairo/lib/libcairo.2.dylib

Trace/BPT trap: 5
dyn-209-2-232-172:bin HannahJaneCohen$ ./VisualSFM 
dyld: lazy symbol binding failed: Symbol not found: _cairo_xlib_surface_create
  Referenced from: /usr/local/opt/gtk+/lib/libgdk-x11-2.0.0.dylib
  Expected in: /usr/local/opt/cairo/lib/libcairo.2.dylib

dyld: Symbol not found: _cairo_xlib_surface_create
  Referenced from: /usr/local/opt/gtk+/lib/libgdk-x11-2.0.0.dylib
  Expected in: /usr/local/opt/cairo/lib/libcairo.2.dylib

Trace/BPT trap: 5

Thanks!

**Comment by hopexiao** [comment]
same problem, have u settle this?

**Comment by saiganeshb** [comment]
Hi, you can see my comment at https://github.com/luckybulldozer/VisualSFM_OS_X_Installer/issues/7#issuecomment-190457647 if you're still stuck to try new options.

**Comment by ealho** [comment]
Hi all! I have the same problem. Tried the solution proposed on #7 comment by saiganeshb, but as it seems, the Xquartz version bug was already fixed in the last installer script version but I still get the same error, even with XQuartz 2.7.8. I am using a OS X Yosemite 10.10.5.  Has anyone a different solution for that?

Many thanks!

**Comment by tonisvain** [comment]
Same problem:


OS X 10.10.5
XQuartz 2.7.8.
gtk+ 2.24.28
cairo 1.14.12
ShiftGPU commit: [b46bd5b8cc5cfdc1dc163444b72c705569800b6d](https://github.com/pitzer/SiftGPU/commit/b46bd5b8cc5cfdc1dc163444b72c705569800b6d)

```
$ /Users/username/vsfm/bin/VisualSFM ; exit;
(process:85193): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
dyld: lazy symbol binding failed: Symbol not found: _cairo_xlib_surface_create
  Referenced from: /usr/local/opt/gtk+/lib/libgdk-x11-2.0.0.dylib
  Expected in: /usr/local/opt/cairo/lib/libcairo.2.dylib

dyld: Symbol not found: _cairo_xlib_surface_create
  Referenced from: /usr/local/opt/gtk+/lib/libgdk-x11-2.0.0.dylib
  Expected in: /usr/local/opt/cairo/lib/libcairo.2.dylib

Trace/BPT trap: 5
logout

[Process completed]
```

Any help is appreciated

**Comment by wu-yuhui** [comment]
Same here...

```
$ ./vsfm/bin/VisualSFM

(process:2310): Gtk-WARNING **: 23:14:44.653: Locale not supported by C library.
	Using the fallback 'C' locale.
dyld: lazy symbol binding failed: Symbol not found: _cairo_xlib_surface_create
  Referenced from: /usr/local/opt/gtk+/lib/libgdk-x11-2.0.0.dylib
  Expected in: /usr/local/opt/cairo/lib/libcairo.2.dylib

dyld: Symbol not found: _cairo_xlib_surface_create
  Referenced from: /usr/local/opt/gtk+/lib/libgdk-x11-2.0.0.dylib
  Expected in: /usr/local/opt/cairo/lib/libcairo.2.dylib

Abort trap: 6
```
on MacOS High Sierra  10.13.3

Any solutions?  Already followed [#7 Comment](https://github.com/luckybulldozer/VisualSFM_OS_X_Installer/issues/7#issuecomment-190457647)'s solution, but still stuck.

**Comment by MStumpp** [comment]
Same problem here.

[https://github.com/luckybulldozer/VisualSFM_OS_X_Installer/issues/7#issuecomment-190457647](url)
did not help.

Any updates?

**Comment by ahmedAlmasri** [comment]
+1

**Comment by ilkedemir** [comment]
[This solution](https://github.com/luckybulldozer/VisualSFM_OS_X_Installer/issues/7#issuecomment-470782046) works in 10.15.
